export const Data = [
	{
		id : 1,
		title : "Brade Butter",
		price :20,
		category :"Brack Fast",
		img_src :"./Food_imgs/food.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
	{
		id : 2,
		title :"Pastta",
		price :23,
		category :"Brack Fast",
		img_src :"./Food_imgs/food1.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
	{
		id : 3,
		title :"Cake" ,
		price :45 ,
		category :"Lanch",
		img_src :"./Food_imgs/food2.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
	{
		id : 4,
		title :"Pizza" ,
		price :30 ,
		category :"Evening",
		img_src :"./Food_imgs/food3.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
	{
		id : 5,
		title : "Pastta",
		price : 15,
		category :"Brack Fast",
		img_src :"./Food_imgs/food5.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
	{
		id : 6,
		title : "Chiken",
		price : 50,
		category :"Dinner",
		img_src :"./Food_imgs/food7.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
	{
		id : 7,
		title :"Noddul" ,
		price : 20,
		category :"Lanch",
		img_src :"./Food_imgs/food8.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
	{
		id : 8,
		title :"Burgar" ,
		price : 40,
		category :"Evening",
		img_src :"./Food_imgs/food7.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
	{
		id : 9,
		title :"Chili Tika" ,
		price : 78,
		category :"Dinner",
		img_src :"./Food_imgs/food9.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
	{
		id : 10,
		title : "Butter Pizza",
		price : 30,
		category :"Lanch",
		img_src :"./Food_imgs/food11.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
	{
		id : 11,
		title : "Extra Butter Pizza" ,
		price : 20,
		category :"Brack Fast",
		img_src :"./Food_imgs/food11.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
		{
		id : 12,
		title : "Chiken Rice" ,
		price : 120,
		category :"Dinner",
		img_src :"./Food_imgs/food14.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
		{
		id : 13,
		title : "Burger Extra" ,
		price : 70,
		category :"Brack Fast",
		img_src :"./Food_imgs/food15.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
		{
		id : 14,
		title : "Dal Rice" ,
		price : 55,
		category :"Dinner",
		img_src :"./Food_imgs/food18.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
		{
		id : 15,
		title : "Tadka Dal" ,
		price : 20,
		category :"Brack Fast",
		img_src :"./Food_imgs/food16.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
		{
		id : 16,
		title : "Chilli Pizza" ,
		price : 90,
		category :"Lanch",
		img_src :"./Food_imgs/food22.jpg",
		description:"Lorem ipsum dolor sit amet ipsum consectetur",
		sub_description :"ipsum dolor sit amet ipsum",
	},
]